blueprint:
  name: Z2M - Sonoff SNZB-01P Zigbee Wireless Switch 
  description: Automate your Sonoff SNZB-01P Zigbee Wireless Switch via Zigbee2MQTT. 
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic of the Sonoff SNZB-01P
      default: zigbee2mqtt/<device name>
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
          multiple: false
          sort: false
          custom_value: false
    single_press:
      name: On Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: On Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: On Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
mode: !input mode
max_exceeded: silent
trigger:
  - platform: mqtt
    topic: !input mqtt_topic
condition:
- condition: template
  value_template: '{{ trigger.to_state.state in ("single","double","long") }}'
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input single_press
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input double_press
      - conditions:
          - "{{ command == 'long' }}"
        sequence: !input long_press