blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01P Zigbee Wireless Switch 
  description: Automate your Sonoff SNZB-01P Zigbee Wireless Switch via Zigbee2MQTT. 
  domain: automation
  input:
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
          multiple: false
          sort: false
          custom_value: false
    switch:
      name: Sonoff SNZB-01P Zigbee Wireless Switch
      description: Sonoff SNZB-01P Zigbee Wireless Switch to use
      selector:
        device:
          integration: mqtt
          manufacturer: eWeLink
          multiple: false
    single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
mode: !input mode
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input switch
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input single_press
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input double_press
      - conditions:
          - "{{ command == 'long' }}"
        sequence: !input long_press